version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-alpine
  influxdb:
    image: influxdb:1.7-alpine
    environment:
      - INFLUXDB_DB=fixm
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
  sos-journaler:
    image: syncorswim/sos-journaler
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE_NAME=fixm
      - INFLUXDB_HOSTNAME=influxdb
      - INFLUXDB_DB=fixm
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
    restart: unless-stopped
  sos-swim-consumer:
    image: syncorswim/sos-swim-consumer
    command: >-
      --swim-broker-url "tcps://ems2.swim.faa.gov:55443"
      --swim-queue ${SWIM_QUEUE}
      --swim-connection-factory ${SWIM_CONNECTION_FACTORY}
      --swim-vpn "FDPS"
      --rabbitmq-host "rabbitmq"
      --rabbitmq-queue-name "fixm"
    environment:
      - SWIM_BROKER_URL=tcps://ems2.swim.faa.gov:55443
      - SWIM_VPN=FDPS
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE_NAME=fixm
      - SWIM_CONNECTION_FACTORY
      - SWIM_QUEUE
      - SWIM_USERNAME
      - SWIM_PASSWORD
    restart: unless-stopped
