version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-alpine
  influxdb:
    image: influxdb:1.7-alpine
    environment:
      - INFLUXDB_DB=fixm
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
    ports:
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb/
  chronograf:
    image: chronograf:1.7-alpine
    ports:
      - 8888:8888
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=user
      - INFLUXDB_PASSWORD=password
  sos-journaler:
    image: syncorswim/sos-journaler
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE_NAME=fixm
      - INFLUXDB_HOSTNAME=influxdb
      - INFLUXDB_DB=fixm
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
      - INFLUXDB_RETENTION_DURATION=1d
    restart: unless-stopped
    build: ./
  sos-swim-consumer:
    image: syncorswim/sos-swim-consumer
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE_NAME=fixm
      - SWIM_BROKER_URL
      - SWIM_VPN
      - SWIM_CONNECTION_FACTORY
      - SWIM_QUEUE
      - SWIM_USERNAME
      - SWIM_PASSWORD
    restart: unless-stopped

volumes:
  influxdb-data:
